// frontend/components/chat-input.tsx
'use client';

import { useState } from 'react';
import { Send, X } from 'lucide-react';
import { Button } from './ui/button';
import { generateResponse } from '@/utils/responseGenerator';
import { DirectAnswer } from './direct-answer';
import { ChartWidget } from './chart-widget';
import { MentalModelFlow } from './mental-model-flow';
import { PinnedItem } from '@/types';
import { motion, AnimatePresence } from 'framer-motion';

/**
 * ChatInput Component
 * Floating chat interface that expands fullscreen with tabs and pinning functionality
 * Based on Figma Chat-Driven Trading Journal design
 */

interface ChatInputProps {
  onOutputGenerated: (output: any) => void;
  onPinItem: (item: PinnedItem) => void;
}

interface ConversationItem {
  type: 'user' | 'assistant';
  content: string;
  output?: any;
  timestamp: Date;
}

export function ChatInput({ onOutputGenerated, onPinItem }: ChatInputProps) {
  const [input, setInput] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [conversation, setConversation] = useState<ConversationItem[]>([]);
  const [activeTab, setActiveTab] = useState<'answer' | 'chart' | 'mental-model'>('answer');
  const [isExpanded, setIsExpanded] = useState(true);

  const hasMessages = conversation.length > 0;
  const currentOutput = conversation.length > 0 ? conversation[conversation.length - 1].output : null;

  const handleSend = () => {
    if (!input.trim() || isLoading) return;

    const userMessage: ConversationItem = {
      type: 'user',
      content: input.trim(),
      timestamp: new Date()
    };

    setConversation(prev => [...prev, userMessage]);
    setIsLoading(true);

    const currentInput = input;
    setInput('');

    // Generate AI response
    setTimeout(() => {
      const response = generateResponse(currentInput);
      
      const assistantMessage: ConversationItem = {
        type: 'assistant',
        content: response.answer || 'Response generated',
        output: response,
        timestamp: new Date()
      };

      setConversation(prev => [...prev, assistantMessage]);
      onOutputGenerated(response);
      setIsLoading(false);
      setIsExpanded(true);
    }, 500);
  };

  const handlePinChart = () => {
    if (!currentOutput) return;
    onPinItem({
      id: Date.now().toString(),
      type: 'chart',
      title: currentOutput.chartType || 'Chart',
      chartType: currentOutput.chartType,
      data: currentOutput,
      timestamp: new Date()
    });
  };

  const handlePinModel = () => {
    if (!currentOutput) return;
    onPinItem({
      id: Date.now().toString(),
      type: 'mental-model',
      title: 'Mental Model',
      data: currentOutput.mentalModel,
      timestamp: new Date()
    });
  };

  const handleClose = () => {
    setConversation([]);
    setInput('');
  };

  const quickQuestions = [
    "Why is my P&L negative this month?",
    "What's my win rate by sector?",
    "Show my biggest losing streaks",
    "Am I overtrading on impulsive setups?",
    "Which time of day am I most profitable?",
    "How does my planned vs impulsive trade performance compare?",
    "What's my average hold time for winners vs losers?",
    "Show my risk-reward ratio trends"
  ];

  return (
    <div className={`fixed left-1/2 -translate-x-1/2 z-20 transition-all duration-300 ${
      hasMessages ? 'top-6 bottom-6 w-[calc(100vw-3rem)]' : 'bottom-6 w-full max-w-3xl px-6'
    }`}>
      <div className="border border-[#a1a1aa] rounded-[32px] bg-[#fafafa] flex flex-col h-full">
        {/* Expanded White Conversation Container - Only visible when there are messages */}
        <AnimatePresence>
          {hasMessages && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              transition={{ type: 'spring', damping: 30, stiffness: 300 }}
              className="flex-1 flex flex-col overflow-hidden"
            >
              {/* Close Button - Top Right */}
              <button
                onClick={handleClose}
                className="absolute top-6 right-6 z-10 bg-[#fca5a5] hover:bg-[#f87171] text-[#2d2d2d] rounded-lg p-2 border-2 border-black shadow-[3px_3px_0px_0px_#000000] transition-all hover:translate-x-[1px] hover:translate-y-[1px] hover:shadow-[2px_2px_0px_0px_#000000] active:translate-x-[3px] active:translate-y-[3px] active:shadow-none"
              >
                <X className="size-5" />
              </button>

              {/* Question Pill at Top */}
              <div className="px-6 pt-6 pb-4 bg-[#fafafa] rounded-t-[32px]">
                <div className="px-6 py-3 rounded-full border-2 border-black bg-[#d4d4d8] inline-block shadow-[3px_3px_0px_0px_#000000]">
                  <p className="text-sm text-[#2d2d2d]">{conversation.filter(item => item.type === 'user').pop()?.content}</p>
                </div>
              </div>

              {/* Answer Area - Full White Background */}
              <div className="flex-1 overflow-y-auto bg-white">
                <div className="h-full">
                  {activeTab === 'answer' && <DirectAnswer output={currentOutput} />}
                  {activeTab === 'chart' && <ChartWidget output={currentOutput} onPin={handlePinChart} />}
                  {activeTab === 'mental-model' && <MentalModelFlow output={currentOutput} onPin={handlePinModel} />}
                </div>
              </div>

              {/* Tab Pills - On white background */}
              <div className="bg-white px-6 py-3 flex items-center justify-center gap-3">
                <button
                  onClick={() => setActiveTab('answer')}
                  className={`relative px-8 py-2.5 rounded-full transition-all text-sm border-2 border-black ${
                    activeTab === 'answer'
                      ? 'bg-[#d9b89c] text-[#2d2d2d] shadow-[4px_4px_0px_0px_#000000]'
                      : 'bg-[#d4d4d8] text-[#2d2d2d] hover:bg-[#e5e5e5] shadow-[2px_2px_0px_0px_#000000]'
                  }`}
                >
                  Answer
                </button>
                <button
                  onClick={() => setActiveTab('chart')}
                  className={`relative px-8 py-2.5 rounded-full transition-all text-sm border-2 border-black ${
                    activeTab === 'chart'
                      ? 'bg-[#e5c9c9] text-[#2d2d2d] shadow-[4px_4px_0px_0px_#000000]'
                      : 'bg-[#d4d4d8] text-[#2d2d2d] hover:bg-[#e5e5e5] shadow-[2px_2px_0px_0px_#000000]'
                  }`}
                >
                  Chart
                </button>
                <button
                  onClick={() => setActiveTab('mental-model')}
                  className={`relative px-8 py-2.5 rounded-full transition-all text-sm border-2 border-black ${
                    activeTab === 'mental-model'
                      ? 'bg-[#d4c4e1] text-[#2d2d2d] shadow-[4px_4px_0px_0px_#000000]'
                      : 'bg-[#d4d4d8] text-[#2d2d2d] hover:bg-[#e5e5e5] shadow-[2px_2px_0px_0px_#000000]'
                  }`}
                >
                  Model
                </button>
              </div>

              {/* Input Area - Below tabs on black background */}
              <div className="bg-[#18181b] px-6 pb-6 pt-3 rounded-b-[32px]">
                <div className="relative bg-[#27272a] rounded-2xl p-3 flex items-center gap-3 border-2 border-black shadow-[4px_4px_0px_0px_#000000]">
                  <div className="flex-1 flex items-center gap-2 bg-[#e5e5e5] rounded-lg px-4 py-3 border-2 border-black">
                    <input
                      value={input}
                      onChange={(e) => setInput(e.target.value)}
                      onKeyDown={(e) => e.key === 'Enter' && handleSend()}
                      placeholder="Ask a follow-up question..."
                      className="flex-1 bg-transparent border-none outline-none text-[#2d2d2d] placeholder:text-[#5a5a5a] font-mono"
                      disabled={isLoading}
                    />
                  </div>
                  <Button 
                    onClick={handleSend}
                    disabled={!input.trim() || isLoading}
                    className="rounded-lg bg-[#3f3f46] hover:bg-[#52525b] text-[#e5e5e5] h-12 px-6 border-2 border-black shadow-[4px_4px_0px_0px_#000000] transition-all hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-[2px_2px_0px_0px_#000000] active:translate-x-[4px] active:translate-y-[4px] active:shadow-none"
                  >
                    <Send className="size-5" />
                  </Button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Black Chat Input Box - Always at bottom, part of the container */}
        {!hasMessages && (
          <div className="p-4">
            {/* Quick Questions */}
            {!input && (
            <div className="mb-2 overflow-x-auto scrollbar-hide">
              <div className="flex gap-2 pb-2 min-w-max px-1">
                {quickQuestions.map((q, i) => {
                  const colors = [
                    'bg-[#3f3f46]',
                    'bg-[#52525b]',
                    'bg-[#27272a]',
                    'bg-[#71717a]',
                    'bg-[#3f3f46]',
                    'bg-[#52525b]',
                    'bg-[#44403c]',
                    'bg-[#27272a]',
                  ];
                  const colorClass = colors[i % colors.length];
                  
                  return (
                    <button
                      key={i}
                      onClick={() => setInput(q)}
                      className={`relative text-xs px-4 py-2 rounded-lg ${colorClass} text-[#e5e5e5] transition-all hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-[1px_1px_0px_0px_#000000] border-2 border-black shadow-[3px_3px_0px_0px_#000000] whitespace-nowrap flex-shrink-0 active:translate-x-[3px] active:translate-y-[3px] active:shadow-none`}
                    >
                      {q}
                    </button>
                  );
                })}
              </div>
            </div>
          )}

          {/* Chat Input Bar */}
          <div className="relative bg-[#18181b] rounded-2xl p-3 flex items-center gap-3 border-2 border-black shadow-[6px_6px_0px_0px_#000000] w-full max-w-3xl mx-auto shrink-0">
            <div className="flex-1 flex items-center gap-2 bg-[#e5e5e5] rounded-lg px-4 py-3 border-2 border-black">
              <input
                value={input}
                onChange={(e) => setInput(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleSend()}
                placeholder="Why is my P&L negative this month, and what should I fix?"
                className="flex-1 bg-transparent border-none outline-none text-[#2d2d2d] placeholder:text-[#5a5a5a] font-mono"
                disabled={isLoading}
              />
            </div>
            <Button 
              onClick={handleSend}
              disabled={!input.trim() || isLoading}
              className="rounded-lg bg-[#3f3f46] hover:bg-[#52525b] text-[#e5e5e5] h-12 px-6 border-2 border-black shadow-[4px_4px_0px_0px_#000000] transition-all hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-[2px_2px_0px_0px_#000000] active:translate-x-[4px] active:translate-y-[4px] active:shadow-none"
            >
              <Send className="size-5" />
            </Button>
          </div>
        </div>
        )}
      </div>
    </div>
  );
}

// frontend/src/routes/trading-journal/ChatInput.svelte
<script lang="ts">
  import { Send, X, ChevronDown, ChevronUp, Pin } from 'lucide-svelte';
  import { fly, slide } from 'svelte/transition';
  import { generateResponse } from '$lib/utils/responseGenerator';
  import type { ConversationItem, PinnedItem } from '$lib/types';
  import DirectAnswer from './DirectAnswer.svelte';
  import ChartWidget from './ChartWidget.svelte';
  import MentalModelFlow from './MentalModelFlow.svelte';

  interface Props {
    onOutputGenerated: (output: any) => void;
    onPinItem: (item: PinnedItem) => void;
  }

  let { onOutputGenerated, onPinItem }: Props = $props();

  let input = $state('');
  let isLoading = $state(false);
  let conversation = $state<ConversationItem[]>([]);
  let activeTab = $state<'answer' | 'chart' | 'mental-model'>('answer');
  let isExpanded = $state(true);

  let hasMessages = $derived(conversation.length > 0);
  let currentOutput = $derived(conversation.length > 0 ? conversation[conversation.length - 1].output : null);
  let lastUserMessage = $derived(conversation.filter(item => item.type === 'user').pop()?.content || '');

  const quickQuestions = [
    "Why is my P&L negative this month?",
    "What's my win rate by sector?",
    "Show my biggest losing streaks",
    "Am I overtrading on impulsive setups?",
    "Which time of day am I most profitable?",
    "How does my planned vs impulsive trade performance compare?",
    "What's my average hold time for winners vs losers?",
    "Show my risk-reward ratio trends"
  ];

  function handleSend() {
    if (!input.trim() || isLoading) return;

    const userMessage: ConversationItem = {
      type: 'user',
      content: input.trim(),
      timestamp: new Date()
    };

    conversation = [...conversation, userMessage];
    isLoading = true;

    const currentInput = input;
    input = '';

    // Generate AI response
    setTimeout(() => {
      const response = generateResponse(currentInput);
      
      const assistantMessage: ConversationItem = {
        type: 'assistant',
        content: response.answer || 'Response generated',
        output: response,
        timestamp: new Date()
      };

      conversation = [...conversation, assistantMessage];
      onOutputGenerated(response);
      isLoading = false;
      isExpanded = true;
    }, 500);
  }

  function handlePinChart() {
    if (!currentOutput) return;
    onPinItem({
      id: Date.now().toString(),
      type: 'chart',
      title: currentOutput.chartType || 'Chart',
      chartType: currentOutput.chartType,
      data: currentOutput,
      timestamp: new Date()
    });
  }

  function handlePinModel() {
    if (!currentOutput) return;
    onPinItem({
      id: Date.now().toString(),
      type: 'mental-model',
      title: 'Mental Model',
      data: currentOutput.mentalModel,
      timestamp: new Date()
    });
  }

  function handleClose() {
    conversation = [];
    input = '';
  }

  function handleKeyDown(event: KeyboardEvent) {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      handleSend();
    }
  }
</script>

<div class="fixed bottom-6 left-1/2 -translate-x-1/2 z-20 w-full max-w-3xl px-6">
  <div 
    class="border border-[#a1a1aa] rounded-[32px] bg-[#fafafa] mt-4 flex flex-col overflow-hidden transition-all duration-300"
    style="height: {hasMessages ? 'calc(100vh - 3rem)' : 'auto'};"
  >
    <!-- Conversation Area - Only show when there are messages -->
    {#if hasMessages}
      <div class="flex-1 flex flex-col overflow-hidden" transition:slide={{ duration: 300 }}>
        <!-- Header -->
        <div class="flex items-center justify-between px-6 py-4 border-b-2 border-black bg-[#b4d4e1]">
          <button
            onclick={() => isExpanded = !isExpanded}
            class="flex items-center gap-2 text-[#2d2d2d] hover:text-[#18181b] transition-colors"
          >
            {#if isExpanded}
              <ChevronDown class="size-5" />
            {:else}
              <ChevronUp class="size-5" />
            {/if}
            <span class="text-sm font-bold">
              {isExpanded ? 'Collapse' : 'Expand'} response
            </span>
          </button>
          
          <div class="flex items-center gap-2">
            {#if activeTab === 'chart'}
              <button
                onclick={handlePinChart}
                class="text-xs px-3 py-2 rounded hover:bg-white/50 transition-colors flex items-center gap-1"
              >
                <Pin class="size-4" />
                Pin Chart
              </button>
            {/if}
            {#if activeTab === 'mental-model'}
              <button
                onclick={handlePinModel}
                class="text-xs px-3 py-2 rounded hover:bg-white/50 transition-colors flex items-center gap-1"
              >
                <Pin class="size-4" />
                Pin Model
              </button>
            {/if}
            <button
              onclick={handleClose}
              class="text-[#2d2d2d] hover:text-[#18181b] p-2"
            >
              <X class="size-4" />
            </button>
          </div>
        </div>

        <!-- Content Area -->
        {#if isExpanded}
          <div class="flex-1 flex flex-col overflow-hidden bg-white">
            <!-- User Message -->
            <div class="p-6 bg-[#fafafa]">
              <div class="flex justify-end">
                <div class="max-w-[80%] px-4 py-3 rounded-2xl border-2 border-black bg-[#3f3f46] text-white shadow-[3px_3px_0px_0px_#000000]">
                  <p class="text-sm">{lastUserMessage}</p>
                </div>
              </div>
            </div>

            <!-- Response Content Box -->
            <div class="flex-1 overflow-y-auto bg-white">
              {#if activeTab === 'answer'}
                <DirectAnswer output={currentOutput} />
              {:else if activeTab === 'chart'}
                <ChartWidget output={currentOutput} onPin={handlePinChart} />
              {:else if activeTab === 'mental-model'}
                <MentalModelFlow output={currentOutput} onPin={handlePinModel} />
              {/if}
            </div>

            <!-- Tab Pills at Bottom -->
            <div class="flex items-center justify-center gap-3 bg-[#fafafa] py-3">
              <button
                onclick={() => activeTab = 'answer'}
                class="relative px-8 py-3 rounded-full transition-all text-sm font-medium border-2 border-black {activeTab === 'answer'
                  ? 'bg-[#d9b89c] text-[#2d2d2d] shadow-[4px_4px_0px_0px_#000000]'
                  : 'bg-white text-[#5a5a5a] hover:bg-[#f5f5f5] shadow-[2px_2px_0px_0px_#000000]'}"
              >
                Answer
              </button>
              <button
                onclick={() => activeTab = 'chart'}
                class="relative px-8 py-3 rounded-full transition-all text-sm font-medium border-2 border-black {activeTab === 'chart'
                  ? 'bg-[#e5c9c9] text-[#2d2d2d] shadow-[4px_4px_0px_0px_#000000]'
                  : 'bg-white text-[#5a5a5a] hover:bg-[#f5f5f5] shadow-[2px_2px_0px_0px_#000000]'}"
              >
                Chart
              </button>
              <button
                onclick={() => activeTab = 'mental-model'}
                class="relative px-8 py-3 rounded-full transition-all text-sm font-medium border-2 border-black {activeTab === 'mental-model'
                  ? 'bg-[#d4c4e1] text-[#2d2d2d] shadow-[4px_4px_0px_0px_#000000]'
                  : 'bg-white text-[#5a5a5a] hover:bg-[#f5f5f5] shadow-[2px_2px_0px_0px_#000000]'}"
              >
                Model
              </button>
            </div>
          </div>
        {/if}
      </div>
    {/if}

    <!-- Input Section - Always visible at bottom -->
    <div class="p-4">
      <!-- Quick Questions -->
      {#if !input && !hasMessages}
        <div class="mb-2 overflow-x-auto scrollbar-hide">
          <div class="flex gap-2 pb-2 min-w-max px-1">
            {#each quickQuestions as q, i}
              {@const colors = [
                'bg-[#3f3f46]',
                'bg-[#52525b]',
                'bg-[#27272a]',
                'bg-[#71717a]',
                'bg-[#3f3f46]',
                'bg-[#52525b]',
                'bg-[#44403c]',
                'bg-[#27272a]',
              ]}
              {@const colorClass = colors[i % colors.length]}
              <button
                onclick={() => input = q}
                class="relative text-xs px-4 py-2 rounded-lg {colorClass} text-[#e5e5e5] transition-all hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-[1px_1px_0px_0px_#000000] border-2 border-black shadow-[3px_3px_0px_0px_#000000] whitespace-nowrap flex-shrink-0 active:translate-x-[3px] active:translate-y-[3px] active:shadow-none"
              >
                {q}
              </button>
            {/each}
          </div>
        </div>
      {/if}

      <!-- Chat Input Bar -->
      <div class="relative bg-[#18181b] rounded-2xl p-3 flex items-center gap-3 border-2 border-black shadow-[6px_6px_0px_0px_#000000]">
        <div class="flex-1 flex items-center gap-2 bg-[#e5e5e5] rounded-lg px-4 py-3 border-2 border-black">
          <input
            bind:value={input}
            onkeydown={handleKeyDown}
            placeholder="Why is my P&L negative this month, and what should I fix?"
            class="flex-1 bg-transparent border-none outline-none text-[#2d2d2d] placeholder:text-[#5a5a5a] font-mono"
            disabled={isLoading}
          />
        </div>
        <button 
          onclick={handleSend}
          disabled={!input.trim() || isLoading}
          class="rounded-lg bg-[#3f3f46] hover:bg-[#52525b] text-[#e5e5e5] h-12 px-6 border-2 border-black shadow-[4px_4px_0px_0px_#000000] transition-all hover:translate-x-[2px] hover:translate-y-[2px] hover:shadow-[2px_2px_0px_0px_#000000] active:translate-x-[4px] active:translate-y-[4px] active:shadow-none disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <Send class="size-5" />
        </button>
      </div>
    </div>
  </div>
</div>

<style>
  .scrollbar-hide {
    -ms-overflow-style: none;
    scrollbar-width: none;
  }
  .scrollbar-hide::-webkit-scrollbar {
    display: none;
  }
</style>
